spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/cogniq_notification
    username: postgres
    password: postgres123
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
  mail:
    host: localhost
    port: 1025
    properties:
      mail:
        smtp:
          auth: false

cogniq:
  jwt:
    secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
  notification:
    from-email: noreply@cogniq.local
    from-name: CogniQ Flow (Dev)
